export const IMAGES = {
    
    user : require('../assets/images/user.png'),
    card : require('../assets/images/card.png'),
    card1 : require('../assets/images/card1.png'),
    appname : require('../assets/images/skalalogo.png'),
    headerlogo : require('../assets/images/logo.png'),
    google2 : require('../assets/images/icons/google2.png'),
    facebook : require('../assets/images/icons/facebook.png'),
    Home: require('../assets/images/icons/home.png'),
    Home4: require('../assets/images/icons/home4.png'),
    heart: require('../assets/images/icons/heart.png'),
    mycart: require('../assets/images/icons/shopping2.png'),
    Category: require('../assets/images/icons/document.png'),
    user2: require('../assets/images/icons/user.png'),
    user3: require('../assets/images/icons/user4.png'),
    grid3: require('../assets/images/icons/grid3.png'),
    grid4: require('../assets/images/icons/grid4.png'),
    grid5: require('../assets/images/icons/grid5.png'),
    shose: require('../assets/images/icons/shose.png'),
    ball: require('../assets/images/icons/bell2.png'),
    ball2: require('../assets/images/icons/bell.png'),
    close: require('../assets/images/icons/close.png'),
    check: require('../assets/images/icons/check.png'),
    check2: require('../assets/images/icons/check2.png'),
    check3: require('../assets/images/icons/check3.png'),
    check4: require('../assets/images/icons/check4.png'),
    delete: require('../assets/images/icons/delete.png'),
    Chat: require('../assets/images/icons/Chat.png'),
    Star: require('../assets/images/icons/Star.png'),
    Star4: require('../assets/images/icons/star4.png'),
    wallet: require('../assets/images/icons/wallet.png'),
    wallet2: require('../assets/images/icons/wallet2.png'),
    Location: require('../assets/images/icons/Location.png'),
    Filter: require('../assets/images/icons/Filter.png'),
    Notification: require('../assets/images/icons/Notification.png'),
    search: require('../assets/images/icons/search.png'),
    list: require('../assets/images/icons/list.png'),
    list2: require('../assets/images/icons/list2.png'),
    grid: require('../assets/images/icons/grid.png'),
    arrowup: require('../assets/images/icons/arrowup.png'),
    filter2: require('../assets/images/icons/filter2.png'),
    filter3: require('../assets/images/icons/filter3.png'),
    shop: require('../assets/images/icons/shop.png'),
    Bag: require('../assets/images/icons/Bag.png'),
    plus: require('../assets/images/icons/plus.png'),
    dollar: require('../assets/images/icons/dollar.png'),
    payment: require('../assets/images/icons/payment.png'),
    folder: require('../assets/images/icons/folder.png'),
    bank: require('../assets/images/icons/bank.png'),
    shieldcheck: require('../assets/images/icons/shieldcheck.png'),
    card2: require('../assets/images/icons/card2.png'),
    write: require('../assets/images/icons/write.png'),
    downaeeowsmall: require('../assets/images/icons/downaeeowsmall.png'),
    home: require('../assets/images/icons/home4.png'),
    producta: require('../assets/images/icons/producta.png'),
    components: require('../assets/images/icons/components.png'),
    star: require('../assets/images/icons/star2.png'), 
    heart2: require('../assets/images/icons/heart2.png'), 
    order: require('../assets/images/icons/order.png'), 
    shopping: require('../assets/images/icons/shopping3.png'), 
    chat: require('../assets/images/icons/chat2.png'), 
    logout: require('../assets/images/icons/logout.png'), 
    call: require('../assets/images/icons/call.png'), 
    happy: require('../assets/images/icons/happy.png'), 
    send: require('../assets/images/icons/send.png'), 
    volume: require('../assets/images/icons/volume.png'), 
    phone: require('../assets/images/icons/phone.png'), 
    audio: require('../assets/images/icons/audio.png'), 
    audiomute: require('../assets/images/icons/audiomute.png'), 
    sun: require('../assets/images/icons/sun.png'), 
    darkMode: require('../assets/images/icons/moon.png'), 
    fire: require('../assets/images/icons/fire.png'), 
    deliverytruck: require('../assets/images/icons/delivery-truck.png'), 
    deliverytruck2: require('../assets/images/icons/delivery-truck2.png'), 
    savemoney: require('../assets/images/icons/save-money.png'), 
    technicalsupport: require('../assets/images/icons/technical-support.png'), 
    timer: require('../assets/images/icons/timer.png'), 
    offer: require('../assets/images/icons/offer.png'), 
    gift: require('../assets/images/icons/gift1.png'), 
    background: require('../assets/images/icons/background.png'), 
    star7: require('../assets/images/icons/star7.png'), 
    leftarrow: require('../assets/images/icons/leftarrow.png'), 
    map: require('../assets/images/icons/map.png'), 
    savecheck: require('../assets/images/icons/save-check.png'), 
    translation: require('../assets/images/icons/translation.png'), 
    transfer: require('../assets/images/icons/transfer.png'), 

    banner1 : require('../assets/images/item2/hoodietop.png'),
    banner2 : require('../assets/images/item2/orangehoodie.png'),
    banner3 : require('../assets/images/item2/jersey.png'),
    bannerborder1 : require('../assets/images/banner/border1.png'),
    bannerborder2 : require('../assets/images/banner/border2.png'),

    onborder1 : require('../assets/images/onbording/pic1.png'),
    item1: require('../assets/images/item/pic1.png'),
    item2: require('../assets/images/item/pic2.png'),
    item3: require('../assets/images/item/pic3.png'),
    item4: require('../assets/images/item/pic4.png'),
    item5: require('../assets/images/item/pic5.png'),
    item6: require('../assets/images/item/pic6.png'),
    item7: require('../assets/images/item/pic7.png'),
    item8: require('../assets/images/item/pic8.png'),

    jersey:require("../assets/images/item2/jersey.png"),
    greenhoodie:require("../assets/images/item2/greenhoodie.png"),

    item01: require('../assets/images/item/pic11.png'),
    item02: require('../assets/images/item/pic12.png'),
    item03: require('../assets/images/item/pic13.png'),
    item04: require('../assets/images/item/pic14.png'),
    item05: require('../assets/images/item/pic15.png'),
    item06: require('../assets/images/item/pic16.png'),
    item07: require('../assets/images/item/pic17.png'),
    item08: require('../assets/images/item/pic18.png'),
    item09: require('../assets/images/item/pic19.png'),
    item010: require('../assets/images/item/pic20.png'),
    item011: require('../assets/images/item/pic21.png'),
    item012: require('../assets/images/item/pic22.png'),


    casual:require("../assets/images/item2/casual.png"),
    hoodietop:require("../assets/images/item2/hoodietop.png"),
    shortpant:require("../assets/images/item2/shortpant.png"),
    tshirt:require("../assets/images/item2/tshirt.png"),
    orangehoodie:require("../assets/images/item2/orangehoodie.png"),
    manstshirt:require("../assets/images/item2/manstshirt.png"),
    kidshoodies:require("../assets/images/item2/kidsdesign.png"),
    frauentshirt:require("../assets/images/item2/frauentshirt.png"),

    item9: require('../assets/images/item2/pic1.png'),
    item10: require('../assets/images/item2/pic2.png'),
    item11: require('../assets/images/item2/pic3.png'),
    item12: require('../assets/images/item2/pic4.png'),
    item13: require('../assets/images/item2/pic5.png'),
    item14: require('../assets/images/item2/pic6.png'),
    item15: require('../assets/images/item2/pic7.png'),
    item16: require('../assets/images/item2/pic8.png'),
    item17: require('../assets/images/item2/pic9.png'),
    item20: require('../assets/images/item2/pic10.png'),
    item21: require('../assets/images/item2/pic11.png'),
    item22: require('../assets/images/item2/pic12.png'),
    item23: require('../assets/images/item2/pic13.png'),
    item24: require('../assets/images/item2/pic14.png'),

    item18: require('../assets/images/item/pic9.png'),
    item19: require('../assets/images/item/pic10.png'),


    brand1: require('../assets/images/brand/pic1.png'),
    brand2: require('../assets/images/brand/pic2.png'),
    brand3: require('../assets/images/brand/pic3.png'),
    brand4: require('../assets/images/brand/pic4.png'),
    brand5: require('../assets/images/brand/pic5.png'),
    brand6: require('../assets/images/brand/pic6.png'),
    brand7: require('../assets/images/brand/pic7.png'),
    brand8: require('../assets/images/brand/pic8.png'),
    brand9: require('../assets/images/brand/pic9.png'),
    brand10: require('../assets/images/brand/pic10.png'),
    brand11: require('../assets/images/brand/pic11.png'),
    brand12: require('../assets/images/brand/pic12.png'),


    small1: require('../assets/images/small/pic5.png'),
    small2: require('../assets/images/small/pic6.png'),
    small3: require('../assets/images/small/pic7.png'),
    small4: require('../assets/images/small/pic8.png'),
    small5: require('../assets/images/small/pic9.png'),
    small6: require('../assets/images/small/pic10.png'),
    small7: require('../assets/images/small/pic11.png'),

    product1: require('../assets/images/product/pic1.png'),
    product2: require('../assets/images/product/pic2.png'),
    product3: require('../assets/images/product/pic3.png'),
    product4: require('../assets/images/product/pic4.png'),
    product5: require('../assets/images/product/pic5.png'),
    product6: require('../assets/images/product/pic6.png'),
    product7: require('../assets/images/product/pic7.png'),
    product8: require('../assets/images/product/pic8.png'),
    product9: require('../assets/images/product/pic9.png'),
    product10: require('../assets/images/product/pic10.png'),
    product11: require('../assets/images/product/pic11.png'),
    product12: require('../assets/images/product/pic12.png'),
    product13: require('../assets/images/product/pic13.png'),
    product14: require('../assets/images/product/pic14.png'),
    product15: require('../assets/images/product/pic15.png'),

    ads1: require('../assets/images/ads/pic1.png'),
    ads2: require('../assets/images/ads/pic2.png'),
    ads3: require('../assets/images/ads/pic3.png'),
    ads4: require('../assets/images/ads/pic4.png'),
    ads5: require('../assets/images/ads/pic5.png'),
    ads6: require('../assets/images/ads/pic6.png'),
    ads7: require('../assets/images/ads/pic7.png'),
    ads8: require('../assets/images/ads/pic8.png'),
    ads9: require('../assets/images/ads/pic9.png'),
    ads10: require('../assets/images/ads/pic10.png'),
    ads11: require('../assets/images/ads/pic11.png'),

    offer1:require("../assets/images/item2/offer1.png"),
    offer2:require('../assets/images/item2/offer2.png'),

    flags1: require('../assets/images/flags/pic1.png'),
    flags2: require('../assets/images/flags/pic2.png'),
    flags3: require('../assets/images/flags/pic3.png'),
    flags4: require('../assets/images/flags/pic4.png'),
    flags5: require('../assets/images/flags/pic5.png'),
    flags6: require('../assets/images/flags/pic6.png'),
    flags7: require('../assets/images/flags/pic7.png'),
    flags8: require('../assets/images/flags/pic8.png'),
    flags9: require('../assets/images/flags/pic9.png'),
    flags10: require('../assets/images/flags/pic10.png'),
    flags11: require('../assets/images/flags/pic11.png'),
    flags12: require('../assets/images/flags/pic12.png'),
    flags13: require('../assets/images/flags/pic13.png'),
    flags14: require('../assets/images/flags/pic14.png'),

    LED1: require('../assets/images/televisions/pic1.png'),
    LED2: require('../assets/images/televisions/pic2.png'),
    LED3: require('../assets/images/televisions/pic3.png'),
    LED4: require('../assets/images/televisions/pic4.png'),

}